#selenium grid
selenium.grid.enabled=true
selenium.grid.urlFormat=http://%s:4444/wd/hub
selenium.grid.hubHost=localhost

#browser
browser=chrome

#application
orangeHrm.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
headless=false